parser:
  infer_types: true

generator:
  features:
    enable:
      - "paths/client"
      - "client/request/validation"
    disable_all: true
  filters:
    path_regex: ".*(?:v4/integrations|v1/groups|v2/access-flows|v1/access-scopes|v3/connectors|v2/users).*"