// Code generated by ogen, DO NOT EDIT.

package client

// AddGroupMemberV1Params is parameters of addGroupMemberV1 operation.
type AddGroupMemberV1Params struct {
	Email string
	ID    string
}

// DeleteAccessFlowV2Params is parameters of deleteAccessFlowV2 operation.
type DeleteAccessFlowV2Params struct {
	ID string
}

// DeleteAccessScopesV1Params is parameters of deleteAccessScopesV1 operation.
type DeleteAccessScopesV1Params struct {
	ID string
}

// DeleteBundleV2Params is parameters of deleteBundleV2 operation.
type DeleteBundleV2Params struct {
	ID string
}

// DeleteConnectorV3Params is parameters of deleteConnectorV3 operation.
type DeleteConnectorV3Params struct {
	ID string
}

// DeleteGroupV1Params is parameters of deleteGroupV1 operation.
type DeleteGroupV1Params struct {
	ID string
}

// DeleteIntegrationV4Params is parameters of deleteIntegrationV4 operation.
type DeleteIntegrationV4Params struct {
	ID string
}

// GetAccessFlowV2Params is parameters of getAccessFlowV2 operation.
type GetAccessFlowV2Params struct {
	ID string
}

// GetAccessScopesV1Params is parameters of getAccessScopesV1 operation.
type GetAccessScopesV1Params struct {
	ID string
}

// GetBundleV2Params is parameters of getBundleV2 operation.
type GetBundleV2Params struct {
	ID string
}

// GetConnectorV3Params is parameters of getConnectorV3 operation.
type GetConnectorV3Params struct {
	ID string
}

// GetGroupV1Params is parameters of getGroupV1 operation.
type GetGroupV1Params struct {
	ID string
}

// GetIntegrationsByIdV4Params is parameters of getIntegrationsByIdV4 operation.
type GetIntegrationsByIdV4Params struct {
	ID string
}

// GetUserParams is parameters of getUser operation.
type GetUserParams struct {
	ID string
}

// ListAccessFlowsV2Params is parameters of listAccessFlowsV2 operation.
type ListAccessFlowsV2Params struct {
	Limit     OptInt32
	PageToken OptNilString
}

// ListAccessScopesV1Params is parameters of listAccessScopesV1 operation.
type ListAccessScopesV1Params struct {
	Limit     OptInt32
	Name      OptNilString
	PageToken OptNilString
}

// ListBundlesV2Params is parameters of listBundlesV2 operation.
type ListBundlesV2Params struct {
	Limit     OptInt32
	Name      OptNilString
	PageToken OptNilString
}

// ListConnectorsV3Params is parameters of listConnectorsV3 operation.
type ListConnectorsV3Params struct {
	Limit     OptInt32
	PageToken OptNilString
	Status    OptNilStringArray
}

// ListGroupMembersV1Params is parameters of listGroupMembersV1 operation.
type ListGroupMembersV1Params struct {
	ID        string
	Limit     OptInt32
	PageToken OptNilString
}

// ListGroupsV1Params is parameters of listGroupsV1 operation.
type ListGroupsV1Params struct {
	Limit     OptInt32
	Name      OptNilString
	PageToken OptNilString
}

// ListIntegrationsV4Params is parameters of listIntegrationsV4 operation.
type ListIntegrationsV4Params struct {
	Category    OptNilStringArray
	ConnectorID OptNilStringArray
	Limit       OptInt32
	Name        OptNilString
	PageToken   OptNilString
	Status      OptNilStringArray
	Type        OptNilStringArray
}

// RemoveGroupMemberV1Params is parameters of removeGroupMemberV1 operation.
type RemoveGroupMemberV1Params struct {
	Email string
	ID    string
}

// UpdateAccessFlowV2Params is parameters of updateAccessFlowV2 operation.
type UpdateAccessFlowV2Params struct {
	ID string
}

// UpdateAccessScopesV1Params is parameters of updateAccessScopesV1 operation.
type UpdateAccessScopesV1Params struct {
	ID string
}

// UpdateBundleV2Params is parameters of updateBundleV2 operation.
type UpdateBundleV2Params struct {
	ID string
}

// UpdateConnectorV3Params is parameters of updateConnectorV3 operation.
type UpdateConnectorV3Params struct {
	ID string
}

// UpdateGroupMembersV1Params is parameters of updateGroupMembersV1 operation.
type UpdateGroupMembersV1Params struct {
	ID string
}

// UpdateGroupV1Params is parameters of updateGroupV1 operation.
type UpdateGroupV1Params struct {
	ID string
}

// UpdateIntegrationV4Params is parameters of updateIntegrationV4 operation.
type UpdateIntegrationV4Params struct {
	ID string
}
