/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aponoapi

import (
	"encoding/json"
)

// checks if the AccessFlowTerraformV1Settings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccessFlowTerraformV1Settings{}

// AccessFlowTerraformV1Settings struct for AccessFlowTerraformV1Settings
type AccessFlowTerraformV1Settings struct {
	RequireJustificationOnRequestAgain NullableBool `json:"require_justification_on_request_again,omitempty"`
	RequireAllApprovers                NullableBool `json:"require_all_approvers,omitempty"`
	RequireApproverJustification       NullableBool `json:"require_approver_justification,omitempty"`
	ApproverCannotApproveHimself       NullableBool `json:"approver_cannot_approve_himself,omitempty"`
}

// NewAccessFlowTerraformV1Settings instantiates a new AccessFlowTerraformV1Settings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessFlowTerraformV1Settings() *AccessFlowTerraformV1Settings {
	this := AccessFlowTerraformV1Settings{}
	return &this
}

// NewAccessFlowTerraformV1SettingsWithDefaults instantiates a new AccessFlowTerraformV1Settings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessFlowTerraformV1SettingsWithDefaults() *AccessFlowTerraformV1Settings {
	this := AccessFlowTerraformV1Settings{}
	return &this
}

// GetRequireJustificationOnRequestAgain returns the RequireJustificationOnRequestAgain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccessFlowTerraformV1Settings) GetRequireJustificationOnRequestAgain() bool {
	if o == nil || IsNil(o.RequireJustificationOnRequestAgain.Get()) {
		var ret bool
		return ret
	}
	return *o.RequireJustificationOnRequestAgain.Get()
}

// GetRequireJustificationOnRequestAgainOk returns a tuple with the RequireJustificationOnRequestAgain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccessFlowTerraformV1Settings) GetRequireJustificationOnRequestAgainOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequireJustificationOnRequestAgain.Get(), o.RequireJustificationOnRequestAgain.IsSet()
}

// HasRequireJustificationOnRequestAgain returns a boolean if a field has been set.
func (o *AccessFlowTerraformV1Settings) HasRequireJustificationOnRequestAgain() bool {
	if o != nil && o.RequireJustificationOnRequestAgain.IsSet() {
		return true
	}

	return false
}

// SetRequireJustificationOnRequestAgain gets a reference to the given NullableBool and assigns it to the RequireJustificationOnRequestAgain field.
func (o *AccessFlowTerraformV1Settings) SetRequireJustificationOnRequestAgain(v bool) {
	o.RequireJustificationOnRequestAgain.Set(&v)
}

// SetRequireJustificationOnRequestAgainNil sets the value for RequireJustificationOnRequestAgain to be an explicit nil
func (o *AccessFlowTerraformV1Settings) SetRequireJustificationOnRequestAgainNil() {
	o.RequireJustificationOnRequestAgain.Set(nil)
}

// UnsetRequireJustificationOnRequestAgain ensures that no value is present for RequireJustificationOnRequestAgain, not even an explicit nil
func (o *AccessFlowTerraformV1Settings) UnsetRequireJustificationOnRequestAgain() {
	o.RequireJustificationOnRequestAgain.Unset()
}

// GetRequireAllApprovers returns the RequireAllApprovers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccessFlowTerraformV1Settings) GetRequireAllApprovers() bool {
	if o == nil || IsNil(o.RequireAllApprovers.Get()) {
		var ret bool
		return ret
	}
	return *o.RequireAllApprovers.Get()
}

// GetRequireAllApproversOk returns a tuple with the RequireAllApprovers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccessFlowTerraformV1Settings) GetRequireAllApproversOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequireAllApprovers.Get(), o.RequireAllApprovers.IsSet()
}

// HasRequireAllApprovers returns a boolean if a field has been set.
func (o *AccessFlowTerraformV1Settings) HasRequireAllApprovers() bool {
	if o != nil && o.RequireAllApprovers.IsSet() {
		return true
	}

	return false
}

// SetRequireAllApprovers gets a reference to the given NullableBool and assigns it to the RequireAllApprovers field.
func (o *AccessFlowTerraformV1Settings) SetRequireAllApprovers(v bool) {
	o.RequireAllApprovers.Set(&v)
}

// SetRequireAllApproversNil sets the value for RequireAllApprovers to be an explicit nil
func (o *AccessFlowTerraformV1Settings) SetRequireAllApproversNil() {
	o.RequireAllApprovers.Set(nil)
}

// UnsetRequireAllApprovers ensures that no value is present for RequireAllApprovers, not even an explicit nil
func (o *AccessFlowTerraformV1Settings) UnsetRequireAllApprovers() {
	o.RequireAllApprovers.Unset()
}

// GetRequireApproverJustification returns the RequireApproverJustification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccessFlowTerraformV1Settings) GetRequireApproverJustification() bool {
	if o == nil || IsNil(o.RequireApproverJustification.Get()) {
		var ret bool
		return ret
	}
	return *o.RequireApproverJustification.Get()
}

// GetRequireApproverJustificationOk returns a tuple with the RequireApproverJustification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccessFlowTerraformV1Settings) GetRequireApproverJustificationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequireApproverJustification.Get(), o.RequireApproverJustification.IsSet()
}

// HasRequireApproverJustification returns a boolean if a field has been set.
func (o *AccessFlowTerraformV1Settings) HasRequireApproverJustification() bool {
	if o != nil && o.RequireApproverJustification.IsSet() {
		return true
	}

	return false
}

// SetRequireApproverJustification gets a reference to the given NullableBool and assigns it to the RequireApproverJustification field.
func (o *AccessFlowTerraformV1Settings) SetRequireApproverJustification(v bool) {
	o.RequireApproverJustification.Set(&v)
}

// SetRequireApproverJustificationNil sets the value for RequireApproverJustification to be an explicit nil
func (o *AccessFlowTerraformV1Settings) SetRequireApproverJustificationNil() {
	o.RequireApproverJustification.Set(nil)
}

// UnsetRequireApproverJustification ensures that no value is present for RequireApproverJustification, not even an explicit nil
func (o *AccessFlowTerraformV1Settings) UnsetRequireApproverJustification() {
	o.RequireApproverJustification.Unset()
}

// GetApproverCannotApproveHimself returns the ApproverCannotApproveHimself field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AccessFlowTerraformV1Settings) GetApproverCannotApproveHimself() bool {
	if o == nil || IsNil(o.ApproverCannotApproveHimself.Get()) {
		var ret bool
		return ret
	}
	return *o.ApproverCannotApproveHimself.Get()
}

// GetApproverCannotApproveHimselfOk returns a tuple with the ApproverCannotApproveHimself field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AccessFlowTerraformV1Settings) GetApproverCannotApproveHimselfOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApproverCannotApproveHimself.Get(), o.ApproverCannotApproveHimself.IsSet()
}

// HasApproverCannotApproveHimself returns a boolean if a field has been set.
func (o *AccessFlowTerraformV1Settings) HasApproverCannotApproveHimself() bool {
	if o != nil && o.ApproverCannotApproveHimself.IsSet() {
		return true
	}

	return false
}

// SetApproverCannotApproveHimself gets a reference to the given NullableBool and assigns it to the ApproverCannotApproveHimself field.
func (o *AccessFlowTerraformV1Settings) SetApproverCannotApproveHimself(v bool) {
	o.ApproverCannotApproveHimself.Set(&v)
}

// SetApproverCannotApproveHimselfNil sets the value for ApproverCannotApproveHimself to be an explicit nil
func (o *AccessFlowTerraformV1Settings) SetApproverCannotApproveHimselfNil() {
	o.ApproverCannotApproveHimself.Set(nil)
}

// UnsetApproverCannotApproveHimself ensures that no value is present for ApproverCannotApproveHimself, not even an explicit nil
func (o *AccessFlowTerraformV1Settings) UnsetApproverCannotApproveHimself() {
	o.ApproverCannotApproveHimself.Unset()
}

func (o AccessFlowTerraformV1Settings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccessFlowTerraformV1Settings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.RequireJustificationOnRequestAgain.IsSet() {
		toSerialize["require_justification_on_request_again"] = o.RequireJustificationOnRequestAgain.Get()
	}
	if o.RequireAllApprovers.IsSet() {
		toSerialize["require_all_approvers"] = o.RequireAllApprovers.Get()
	}
	if o.RequireApproverJustification.IsSet() {
		toSerialize["require_approver_justification"] = o.RequireApproverJustification.Get()
	}
	if o.ApproverCannotApproveHimself.IsSet() {
		toSerialize["approver_cannot_approve_himself"] = o.ApproverCannotApproveHimself.Get()
	}
	return toSerialize, nil
}

type NullableAccessFlowTerraformV1Settings struct {
	value *AccessFlowTerraformV1Settings
	isSet bool
}

func (v NullableAccessFlowTerraformV1Settings) Get() *AccessFlowTerraformV1Settings {
	return v.value
}

func (v *NullableAccessFlowTerraformV1Settings) Set(val *AccessFlowTerraformV1Settings) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessFlowTerraformV1Settings) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessFlowTerraformV1Settings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessFlowTerraformV1Settings(val *AccessFlowTerraformV1Settings) *NullableAccessFlowTerraformV1Settings {
	return &NullableAccessFlowTerraformV1Settings{value: val, isSet: true}
}

func (v NullableAccessFlowTerraformV1Settings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessFlowTerraformV1Settings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
