/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aponoapi

import (
	"encoding/json"
)

// checks if the WebhookManualTriggerTerraformModelAuthenticationConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookManualTriggerTerraformModelAuthenticationConfig{}

// WebhookManualTriggerTerraformModelAuthenticationConfig struct for WebhookManualTriggerTerraformModelAuthenticationConfig
type WebhookManualTriggerTerraformModelAuthenticationConfig struct {
	Oauth NullableWebhookAuthenticationConfigTerraformModelOauth `json:"oauth,omitempty"`
}

// NewWebhookManualTriggerTerraformModelAuthenticationConfig instantiates a new WebhookManualTriggerTerraformModelAuthenticationConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookManualTriggerTerraformModelAuthenticationConfig() *WebhookManualTriggerTerraformModelAuthenticationConfig {
	this := WebhookManualTriggerTerraformModelAuthenticationConfig{}
	return &this
}

// NewWebhookManualTriggerTerraformModelAuthenticationConfigWithDefaults instantiates a new WebhookManualTriggerTerraformModelAuthenticationConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookManualTriggerTerraformModelAuthenticationConfigWithDefaults() *WebhookManualTriggerTerraformModelAuthenticationConfig {
	this := WebhookManualTriggerTerraformModelAuthenticationConfig{}
	return &this
}

// GetOauth returns the Oauth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookManualTriggerTerraformModelAuthenticationConfig) GetOauth() WebhookAuthenticationConfigTerraformModelOauth {
	if o == nil || IsNil(o.Oauth.Get()) {
		var ret WebhookAuthenticationConfigTerraformModelOauth
		return ret
	}
	return *o.Oauth.Get()
}

// GetOauthOk returns a tuple with the Oauth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookManualTriggerTerraformModelAuthenticationConfig) GetOauthOk() (*WebhookAuthenticationConfigTerraformModelOauth, bool) {
	if o == nil {
		return nil, false
	}
	return o.Oauth.Get(), o.Oauth.IsSet()
}

// HasOauth returns a boolean if a field has been set.
func (o *WebhookManualTriggerTerraformModelAuthenticationConfig) HasOauth() bool {
	if o != nil && o.Oauth.IsSet() {
		return true
	}

	return false
}

// SetOauth gets a reference to the given NullableWebhookAuthenticationConfigTerraformModelOauth and assigns it to the Oauth field.
func (o *WebhookManualTriggerTerraformModelAuthenticationConfig) SetOauth(v WebhookAuthenticationConfigTerraformModelOauth) {
	o.Oauth.Set(&v)
}

// SetOauthNil sets the value for Oauth to be an explicit nil
func (o *WebhookManualTriggerTerraformModelAuthenticationConfig) SetOauthNil() {
	o.Oauth.Set(nil)
}

// UnsetOauth ensures that no value is present for Oauth, not even an explicit nil
func (o *WebhookManualTriggerTerraformModelAuthenticationConfig) UnsetOauth() {
	o.Oauth.Unset()
}

func (o WebhookManualTriggerTerraformModelAuthenticationConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookManualTriggerTerraformModelAuthenticationConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Oauth.IsSet() {
		toSerialize["oauth"] = o.Oauth.Get()
	}
	return toSerialize, nil
}

type NullableWebhookManualTriggerTerraformModelAuthenticationConfig struct {
	value *WebhookManualTriggerTerraformModelAuthenticationConfig
	isSet bool
}

func (v NullableWebhookManualTriggerTerraformModelAuthenticationConfig) Get() *WebhookManualTriggerTerraformModelAuthenticationConfig {
	return v.value
}

func (v *NullableWebhookManualTriggerTerraformModelAuthenticationConfig) Set(val *WebhookManualTriggerTerraformModelAuthenticationConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookManualTriggerTerraformModelAuthenticationConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookManualTriggerTerraformModelAuthenticationConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookManualTriggerTerraformModelAuthenticationConfig(val *WebhookManualTriggerTerraformModelAuthenticationConfig) *NullableWebhookManualTriggerTerraformModelAuthenticationConfig {
	return &NullableWebhookManualTriggerTerraformModelAuthenticationConfig{value: val, isSet: true}
}

func (v NullableWebhookManualTriggerTerraformModelAuthenticationConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookManualTriggerTerraformModelAuthenticationConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
