/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aponoapi

import (
	"encoding/json"
	"fmt"
)

// checks if the WebhookHttpRequestTypeTerraformModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookHttpRequestTypeTerraformModel{}

// WebhookHttpRequestTypeTerraformModel struct for WebhookHttpRequestTypeTerraformModel
type WebhookHttpRequestTypeTerraformModel struct {
	Url     string                      `json:"url"`
	Method  WebhookMethodTerraformModel `json:"method"`
	Headers map[string]string           `json:"headers,omitempty"`
}

type _WebhookHttpRequestTypeTerraformModel WebhookHttpRequestTypeTerraformModel

// NewWebhookHttpRequestTypeTerraformModel instantiates a new WebhookHttpRequestTypeTerraformModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookHttpRequestTypeTerraformModel(url string, method WebhookMethodTerraformModel) *WebhookHttpRequestTypeTerraformModel {
	this := WebhookHttpRequestTypeTerraformModel{}
	this.Url = url
	this.Method = method
	return &this
}

// NewWebhookHttpRequestTypeTerraformModelWithDefaults instantiates a new WebhookHttpRequestTypeTerraformModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookHttpRequestTypeTerraformModelWithDefaults() *WebhookHttpRequestTypeTerraformModel {
	this := WebhookHttpRequestTypeTerraformModel{}
	return &this
}

// GetUrl returns the Url field value
func (o *WebhookHttpRequestTypeTerraformModel) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookHttpRequestTypeTerraformModel) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookHttpRequestTypeTerraformModel) SetUrl(v string) {
	o.Url = v
}

// GetMethod returns the Method field value
func (o *WebhookHttpRequestTypeTerraformModel) GetMethod() WebhookMethodTerraformModel {
	if o == nil {
		var ret WebhookMethodTerraformModel
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *WebhookHttpRequestTypeTerraformModel) GetMethodOk() (*WebhookMethodTerraformModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *WebhookHttpRequestTypeTerraformModel) SetMethod(v WebhookMethodTerraformModel) {
	o.Method = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookHttpRequestTypeTerraformModel) GetHeaders() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookHttpRequestTypeTerraformModel) GetHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return &o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *WebhookHttpRequestTypeTerraformModel) HasHeaders() bool {
	if o != nil && IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *WebhookHttpRequestTypeTerraformModel) SetHeaders(v map[string]string) {
	o.Headers = v
}

func (o WebhookHttpRequestTypeTerraformModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookHttpRequestTypeTerraformModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["method"] = o.Method
	if o.Headers != nil {
		toSerialize["headers"] = o.Headers
	}
	return toSerialize, nil
}

func (o *WebhookHttpRequestTypeTerraformModel) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"method",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookHttpRequestTypeTerraformModel := _WebhookHttpRequestTypeTerraformModel{}

	err = json.Unmarshal(bytes, &varWebhookHttpRequestTypeTerraformModel)

	if err != nil {
		return err
	}

	*o = WebhookHttpRequestTypeTerraformModel(varWebhookHttpRequestTypeTerraformModel)

	return err
}

type NullableWebhookHttpRequestTypeTerraformModel struct {
	value *WebhookHttpRequestTypeTerraformModel
	isSet bool
}

func (v NullableWebhookHttpRequestTypeTerraformModel) Get() *WebhookHttpRequestTypeTerraformModel {
	return v.value
}

func (v *NullableWebhookHttpRequestTypeTerraformModel) Set(val *WebhookHttpRequestTypeTerraformModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookHttpRequestTypeTerraformModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookHttpRequestTypeTerraformModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookHttpRequestTypeTerraformModel(val *WebhookHttpRequestTypeTerraformModel) *NullableWebhookHttpRequestTypeTerraformModel {
	return &NullableWebhookHttpRequestTypeTerraformModel{value: val, isSet: true}
}

func (v NullableWebhookHttpRequestTypeTerraformModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookHttpRequestTypeTerraformModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
