/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aponoapi

import (
	"encoding/json"
	"fmt"
)

// checks if the WebhookAuthenticationConfigTerraformModelOauth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookAuthenticationConfigTerraformModelOauth{}

// WebhookAuthenticationConfigTerraformModelOauth struct for WebhookAuthenticationConfigTerraformModelOauth
type WebhookAuthenticationConfigTerraformModelOauth struct {
	ClientId         string   `json:"client_id"`
	ClientSecret     string   `json:"client_secret"`
	TokenEndpointUrl string   `json:"token_endpoint_url"`
	Scopes           []string `json:"scopes"`
}

type _WebhookAuthenticationConfigTerraformModelOauth WebhookAuthenticationConfigTerraformModelOauth

// NewWebhookAuthenticationConfigTerraformModelOauth instantiates a new WebhookAuthenticationConfigTerraformModelOauth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookAuthenticationConfigTerraformModelOauth(clientId string, clientSecret string, tokenEndpointUrl string, scopes []string) *WebhookAuthenticationConfigTerraformModelOauth {
	this := WebhookAuthenticationConfigTerraformModelOauth{}
	this.ClientId = clientId
	this.ClientSecret = clientSecret
	this.TokenEndpointUrl = tokenEndpointUrl
	this.Scopes = scopes
	return &this
}

// NewWebhookAuthenticationConfigTerraformModelOauthWithDefaults instantiates a new WebhookAuthenticationConfigTerraformModelOauth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookAuthenticationConfigTerraformModelOauthWithDefaults() *WebhookAuthenticationConfigTerraformModelOauth {
	this := WebhookAuthenticationConfigTerraformModelOauth{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *WebhookAuthenticationConfigTerraformModelOauth) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *WebhookAuthenticationConfigTerraformModelOauth) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *WebhookAuthenticationConfigTerraformModelOauth) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecret returns the ClientSecret field value
func (o *WebhookAuthenticationConfigTerraformModelOauth) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *WebhookAuthenticationConfigTerraformModelOauth) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *WebhookAuthenticationConfigTerraformModelOauth) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetTokenEndpointUrl returns the TokenEndpointUrl field value
func (o *WebhookAuthenticationConfigTerraformModelOauth) GetTokenEndpointUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenEndpointUrl
}

// GetTokenEndpointUrlOk returns a tuple with the TokenEndpointUrl field value
// and a boolean to check if the value has been set.
func (o *WebhookAuthenticationConfigTerraformModelOauth) GetTokenEndpointUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenEndpointUrl, true
}

// SetTokenEndpointUrl sets field value
func (o *WebhookAuthenticationConfigTerraformModelOauth) SetTokenEndpointUrl(v string) {
	o.TokenEndpointUrl = v
}

// GetScopes returns the Scopes field value
func (o *WebhookAuthenticationConfigTerraformModelOauth) GetScopes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value
// and a boolean to check if the value has been set.
func (o *WebhookAuthenticationConfigTerraformModelOauth) GetScopesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scopes, true
}

// SetScopes sets field value
func (o *WebhookAuthenticationConfigTerraformModelOauth) SetScopes(v []string) {
	o.Scopes = v
}

func (o WebhookAuthenticationConfigTerraformModelOauth) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookAuthenticationConfigTerraformModelOauth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_id"] = o.ClientId
	toSerialize["client_secret"] = o.ClientSecret
	toSerialize["token_endpoint_url"] = o.TokenEndpointUrl
	toSerialize["scopes"] = o.Scopes
	return toSerialize, nil
}

func (o *WebhookAuthenticationConfigTerraformModelOauth) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client_id",
		"client_secret",
		"token_endpoint_url",
		"scopes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookAuthenticationConfigTerraformModelOauth := _WebhookAuthenticationConfigTerraformModelOauth{}

	err = json.Unmarshal(bytes, &varWebhookAuthenticationConfigTerraformModelOauth)

	if err != nil {
		return err
	}

	*o = WebhookAuthenticationConfigTerraformModelOauth(varWebhookAuthenticationConfigTerraformModelOauth)

	return err
}

type NullableWebhookAuthenticationConfigTerraformModelOauth struct {
	value *WebhookAuthenticationConfigTerraformModelOauth
	isSet bool
}

func (v NullableWebhookAuthenticationConfigTerraformModelOauth) Get() *WebhookAuthenticationConfigTerraformModelOauth {
	return v.value
}

func (v *NullableWebhookAuthenticationConfigTerraformModelOauth) Set(val *WebhookAuthenticationConfigTerraformModelOauth) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookAuthenticationConfigTerraformModelOauth) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookAuthenticationConfigTerraformModelOauth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookAuthenticationConfigTerraformModelOauth(val *WebhookAuthenticationConfigTerraformModelOauth) *NullableWebhookAuthenticationConfigTerraformModelOauth {
	return &NullableWebhookAuthenticationConfigTerraformModelOauth{value: val, isSet: true}
}

func (v NullableWebhookAuthenticationConfigTerraformModelOauth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookAuthenticationConfigTerraformModelOauth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
