/*
Apono

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aponoapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ApproverPolicyTerraformV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApproverPolicyTerraformV1{}

// ApproverPolicyTerraformV1 struct for ApproverPolicyTerraformV1
type ApproverPolicyTerraformV1 struct {
	GroupsRelationship ApproverPolicyGroupsRelationshipTerraformV1 `json:"groups_relationship"`
	ConditionGroups    []ApproverConditionGroupTerraformV1         `json:"condition_groups"`
}

type _ApproverPolicyTerraformV1 ApproverPolicyTerraformV1

// NewApproverPolicyTerraformV1 instantiates a new ApproverPolicyTerraformV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproverPolicyTerraformV1(groupsRelationship ApproverPolicyGroupsRelationshipTerraformV1, conditionGroups []ApproverConditionGroupTerraformV1) *ApproverPolicyTerraformV1 {
	this := ApproverPolicyTerraformV1{}
	this.GroupsRelationship = groupsRelationship
	this.ConditionGroups = conditionGroups
	return &this
}

// NewApproverPolicyTerraformV1WithDefaults instantiates a new ApproverPolicyTerraformV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproverPolicyTerraformV1WithDefaults() *ApproverPolicyTerraformV1 {
	this := ApproverPolicyTerraformV1{}
	return &this
}

// GetGroupsRelationship returns the GroupsRelationship field value
func (o *ApproverPolicyTerraformV1) GetGroupsRelationship() ApproverPolicyGroupsRelationshipTerraformV1 {
	if o == nil {
		var ret ApproverPolicyGroupsRelationshipTerraformV1
		return ret
	}

	return o.GroupsRelationship
}

// GetGroupsRelationshipOk returns a tuple with the GroupsRelationship field value
// and a boolean to check if the value has been set.
func (o *ApproverPolicyTerraformV1) GetGroupsRelationshipOk() (*ApproverPolicyGroupsRelationshipTerraformV1, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupsRelationship, true
}

// SetGroupsRelationship sets field value
func (o *ApproverPolicyTerraformV1) SetGroupsRelationship(v ApproverPolicyGroupsRelationshipTerraformV1) {
	o.GroupsRelationship = v
}

// GetConditionGroups returns the ConditionGroups field value
func (o *ApproverPolicyTerraformV1) GetConditionGroups() []ApproverConditionGroupTerraformV1 {
	if o == nil {
		var ret []ApproverConditionGroupTerraformV1
		return ret
	}

	return o.ConditionGroups
}

// GetConditionGroupsOk returns a tuple with the ConditionGroups field value
// and a boolean to check if the value has been set.
func (o *ApproverPolicyTerraformV1) GetConditionGroupsOk() ([]ApproverConditionGroupTerraformV1, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConditionGroups, true
}

// SetConditionGroups sets field value
func (o *ApproverPolicyTerraformV1) SetConditionGroups(v []ApproverConditionGroupTerraformV1) {
	o.ConditionGroups = v
}

func (o ApproverPolicyTerraformV1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApproverPolicyTerraformV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["groups_relationship"] = o.GroupsRelationship
	toSerialize["condition_groups"] = o.ConditionGroups
	return toSerialize, nil
}

func (o *ApproverPolicyTerraformV1) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"groups_relationship",
		"condition_groups",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApproverPolicyTerraformV1 := _ApproverPolicyTerraformV1{}

	err = json.Unmarshal(bytes, &varApproverPolicyTerraformV1)

	if err != nil {
		return err
	}

	*o = ApproverPolicyTerraformV1(varApproverPolicyTerraformV1)

	return err
}

type NullableApproverPolicyTerraformV1 struct {
	value *ApproverPolicyTerraformV1
	isSet bool
}

func (v NullableApproverPolicyTerraformV1) Get() *ApproverPolicyTerraformV1 {
	return v.value
}

func (v *NullableApproverPolicyTerraformV1) Set(val *ApproverPolicyTerraformV1) {
	v.value = val
	v.isSet = true
}

func (v NullableApproverPolicyTerraformV1) IsSet() bool {
	return v.isSet
}

func (v *NullableApproverPolicyTerraformV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproverPolicyTerraformV1(val *ApproverPolicyTerraformV1) *NullableApproverPolicyTerraformV1 {
	return &NullableApproverPolicyTerraformV1{value: val, isSet: true}
}

func (v NullableApproverPolicyTerraformV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproverPolicyTerraformV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
